#Server服务端相关配置
server:
  servlet:
    session:
      timeout:  60
    context-path: /Story
  port: 8080
  #Tomcat相关配置
  tomcat:
    uri-encoding: UTF-8

spring:
  #热部署
  devtools:
    restart:
      #热部署生效
      enabled: true
      #设置热部署需要重启的目录
      additional-paths: src\main\java
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
  #freemarker 静态资源配置
  freemarker:
    #设定ftl文件路径
    template-loader-path: classpath:/templates
    #关闭缓存，即时刷新，上线生产环境需要改为true
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .ftl
  #设置静态文件路径，js，css等等
  mvc:
    static-path-pattern: /static/**

